export const TYPES = {
  UserRepository: Symbol.for("UserRepository"),
  CommandBus: Symbol.for("CommandBus"),
  QueryBus: Symbol.for("QueryBus"),
  UserController: Symbol.for("UserController"),
  AuthService: Symbol.for("AuthService"),
  AuthController: Symbol.for("AuthController"),
  UserContext: Symbol.for("UserContext"),
  AuthRepository: Symbol.for("AuthRepository"),
  IoTEventRepository: Symbol.for("IoTEventRepository"),
  RecordingRepository: Symbol.for("RecordingRepository"),
  SocketService: Symbol.for("SocketService"),
  VideoService: Symbol.for("VideoService"),
  IoTController: Symbol.for("IoTController"),
  RecordingController: Symbol.for("RecordingController"),
};
